apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-consumer
  labels:
    app: post-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-consumer
  template:
    metadata:
      labels:
        app: post-consumer
    spec:
      containers:
        - name: post-consumer
          image: post-consumer:latest 
          imagePullPolicy: Never 
          
          command: ["python", "main.py"]
          args:
            - "--kafka_host"
            - "kafka-broker-service:9092"
            
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /app/secrets/service-account.json 
          - name: KAFKA_BROKER 
            valueFrom:
              configMapKeyRef:
                name: post-consumer-config
                key: KAFKA_BROKER
          - name: KAFKA_TOPIC 
            valueFrom:
              configMapKeyRef:
                name: post-consumer-config
                key: KAFKA_TOPIC
          - name: BQ_DATASET
            valueFrom:
              configMapKeyRef:
                name: post-consumer-config
                key: BQ_DATASET
          - name: BQ_TABLE
            valueFrom:
              configMapKeyRef:
                name: post-consumer-config
                key: BQ_TABLE
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: post-consumer-config
                key: MONGO_HOST
          - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                name: post-consumer-config
                key: MONGO_PORT
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: password
          - name: MONGO_DB
            valueFrom:
              configMapKeyRef:
                name: post-consumer-config
                key: MONGO_DB
          - name: MONGO_COLLECTION
            valueFrom:
              configMapKeyRef:
                name: post-consumer-config
                key: MONGO_COLLECTION
            
          volumeMounts:
            - name: gcp-sa-volume
              mountPath: /app/secrets/
              readOnly: true
          
      volumes:
        - name: gcp-sa-volume
          secret:
            secretName: gcp-sa-secret